    Traceback:<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/&#34;,line677,inurlopen<br/><br/>    　　chunked=chunked,<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/&#34;,line426,in_e_request<br/><br/>    　　se_fro,None)<br/><br/>    　　File&#34;<string>&#34;,line3,inraise_from<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/&#34;,line421,in_e_request<br/><br/>    　　httplib_response=response<br/><br/>    　　File&#34;/usr/local/lib/python3.6/http/&#34;,line1331,ingetresponse<br/><br/>    　　in<br/><br/>    　　File&#34;/usr/local/lib/python3.6/http/&#34;,line297,inbegin<br/><br/>    　　version,status,reason=self._read_status<br/><br/>    　　File&#34;/usr/local/lib/python3.6/http/&#34;,line266,in_read_status<br/><br/>    　　raiseReeDisconnected:<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/requests/&#34;,line449,insend<br/><br/>    　　tiut=tiut<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/&#34;,line725,inurlopen<br/><br/>    　　hod,url,error=e,_pool=self,_stacktrace=_info<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/util/&#34;,line403,inincret<br/><br/>    　　aise,error,_stacktrace)<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/packages/&#34;,line734,inreraise<br/><br/>    　　h_traceback<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/&#34;,line677,inurlopen<br/><br/>    　　chunked=chunked,<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/&#34;,line426,in_e_request<br/><br/>    　　se_fro,None)<br/><br/>    　　File&#34;<string>&#34;,line3,inraise_from<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/urllib3/&#34;,line421,in_e_request<br/><br/>    　　httplib_response=response<br/><br/>    　　File&#34;/usr/local/lib/python3.6/http/&#34;,line1331,ingetresponse<br/><br/>    　　in<br/><br/>    　　File&#34;/usr/local/lib/python3.6/http/&#34;,line297,inbegin<br/><br/>    　　version,status,reason=self._read_status<br/><br/>    　　File&#34;/usr/local/lib/python3.6/http/&#34;,line266,in_read_status<br/><br/>    　　raiseReeDisconnected)<br/><br/>    　　Duringhandlingoftheaboveexception,anotherexceptionoccurred:<br/><br/>    　　Traceback:<br/><br/>    　　File&#34;&#34;,line108,in<ule><br/><br/>    　　result=parse<br/><br/>    　　File&#34;&#34;,line15,inparse<br/><br/>    　　Content=download<br/><br/>    　　File&#34;&#34;,line88,indownload<br/><br/>    　　resp=<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/requests/&#34;,line76,inget<br/><br/>    　　returnrequest<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/requests/&#34;,line61,inrequest<br/><br/>    　　uest<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/requests/&#34;,line530,inrequest<br/><br/>    　　resp=d<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/requests/&#34;,line643,insend<br/><br/>    　　r=d<br/><br/>    　　File&#34;/usr/local/lib/python3.6/site-packages/requests/&#34;,line498,insend<br/><br/>    　　raiseConnectionError<br/><br/>    　　nectionError:)<br/><br/></ule></string></string>